/*
 This file was autogenerated by tags.py 
 */

#import "GCEventDetailAttribute.h"

@class GCAddressLine1Attribute;
@class GCAddressLine2Attribute;
@class GCCityAttribute;
@class GCCountryAttribute;
@class GCPostalCodeAttribute;
@class GCStateAttribute;

/**
 
*/
@interface GCAddressAttribute : GCEventDetailAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a address.

 
 @return A new address.
*/
+(instancetype)address;
/// @name Initializing

/** Initializes and returns a address.

 @param value The value as a GCValue object.
 @return A new address.
*/
+(instancetype)addressWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a address.

 @param value The value as an NSString.
 @return A new address.
*/
+(instancetype)addressWithGedcomStringValue:(NSString *)value;

// Properties:
/// . 
@property (nonatomic, strong) GCAddressLine1Attribute *addressLine1;

/// . 
@property (nonatomic, strong) GCAddressLine2Attribute *addressLine2;

/// . 
@property (nonatomic, strong) GCCityAttribute *city;

/// . 
@property (nonatomic, strong) GCStateAttribute *state;

/// . 
@property (nonatomic, strong) GCPostalCodeAttribute *postalCode;

/// . 
@property (nonatomic, strong) GCCountryAttribute *country;


@end
