/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"

@class GCAddressAttribute;
@class GCEmailAddressAttribute;
@class GCFaxNumberAttribute;
@class GCPhoneNumberAttribute;
@class GCWebAddressAttribute;

/**
 
*/
@interface GCCorporationAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a corporation.

 
 @return A new corporation.
*/
+(instancetype)corporation;
/// @name Initializing

/** Initializes and returns a corporation.

 @param value The value as a GCValue object.
 @return A new corporation.
*/
+(instancetype)corporationWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a corporation.

 @param value The value as an NSString.
 @return A new corporation.
*/
+(instancetype)corporationWithGedcomStringValue:(NSString *)value;

// Properties:
/// @name Accessing address structures

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *addressStructures;

/// @name Accessing address structures 

///Also contained in addressStructures. . 
@property (nonatomic, strong) GCAddressAttribute *address;

/// @name Accessing address structures 

///Also contained in addressStructures. . GCPhoneNumberAttribute
@property (nonatomic, strong) NSArray *phoneNumbers;
/// @name Accessing address structures 

///Also contained in addressStructures. . Contains instances of phoneNumbers
@property (nonatomic, strong) NSMutableArray *mutablePhoneNumbers;

/// @name Accessing address structures 

///Also contained in addressStructures. . GCEmailAddressAttribute
@property (nonatomic, strong) NSArray *emailAddresses;
/// @name Accessing address structures 

///Also contained in addressStructures. . Contains instances of emailAddresses
@property (nonatomic, strong) NSMutableArray *mutableEmailAddresses;

/// @name Accessing address structures 

///Also contained in addressStructures. . GCFaxNumberAttribute
@property (nonatomic, strong) NSArray *faxNumbers;
/// @name Accessing address structures 

///Also contained in addressStructures. . Contains instances of faxNumbers
@property (nonatomic, strong) NSMutableArray *mutableFaxNumbers;

/// @name Accessing address structures 

///Also contained in addressStructures. . GCWebAddressAttribute
@property (nonatomic, strong) NSArray *webAddresses;
/// @name Accessing address structures 

///Also contained in addressStructures. . Contains instances of webAddresses
@property (nonatomic, strong) NSMutableArray *mutableWebAddresses;


@end
