/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCEmailAddressAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a emailAddress.

 
 @return A new emailAddress.
*/
+(instancetype)emailAddress;
/// @name Initializing

/** Initializes and returns a emailAddress.

 @param value The value as a GCValue object.
 @return A new emailAddress.
*/
+(instancetype)emailAddressWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a emailAddress.

 @param value The value as an NSString.
 @return A new emailAddress.
*/
+(instancetype)emailAddressWithGedcomStringValue:(NSString *)value;

// Properties:


@end
