/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCFaxNumberAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a faxNumber.

 
 @return A new faxNumber.
*/
+(instancetype)faxNumber;
/// @name Initializing

/** Initializes and returns a faxNumber.

 @param value The value as a GCValue object.
 @return A new faxNumber.
*/
+(instancetype)faxNumberWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a faxNumber.

 @param value The value as an NSString.
 @return A new faxNumber.
*/
+(instancetype)faxNumberWithGedcomStringValue:(NSString *)value;

// Properties:


@end
