/*
 This file was autogenerated by tags.py 
 */

#import "GCRecord.h"

@class GCAnnulmentAttribute;
@class GCCensusAttribute;
@class GCChangeInfoAttribute;
@class GCChildRelationship;
@class GCDivorceAttribute;
@class GCDivorceFiledAttribute;
@class GCEngagementAttribute;
@class GCGenericEventAttribute;
@class GCHusbandRelationship;
@class GCLDSSealingSpouseAttribute;
@class GCMarriageAttribute;
@class GCMarriageBannAttribute;
@class GCMarriageContractAttribute;
@class GCMarriageLicenseAttribute;
@class GCMarriageSettlementAttribute;
@class GCMultimediaEmbeddedAttribute;
@class GCMultimediaReferenceRelationship;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCNumberOfChildrenAttribute;
@class GCRecordIdNumberAttribute;
@class GCSourceCitationRelationship;
@class GCSourceEmbeddedAttribute;
@class GCSubmitterReferenceRelationship;
@class GCUserReferenceNumberAttribute;
@class GCWifeRelationship;

/**
 The family record is used to record marriages, common law marriages, and family unions caused by two people becoming the parents of a child.
*/
@interface GCFamilyRecord : GCRecord

// Methods:
/// @name Initializing

/** Initializes and returns a family.

 @param context The context in which to create the entity.
 @return A new family.
*/
+(instancetype)familyInContext:(GCContext *)context;

// Properties:
/// @name Accessing family events

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *familyEvents;

/// @name Accessing family events 

///Also contained in familyEvents. . GCAnnulmentAttribute
@property (nonatomic, strong) NSArray *annulments;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of annulments
@property (nonatomic, strong) NSMutableArray *mutableAnnulments;

/// @name Accessing family events 

///Also contained in familyEvents. . GCCensusAttribute
@property (nonatomic, strong) NSArray *censuses;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of censuses
@property (nonatomic, strong) NSMutableArray *mutableCensuses;

/// @name Accessing family events 

///Also contained in familyEvents. . GCDivorceAttribute
@property (nonatomic, strong) NSArray *divorces;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of divorces
@property (nonatomic, strong) NSMutableArray *mutableDivorces;

/// @name Accessing family events 

///Also contained in familyEvents. . GCDivorceFiledAttribute
@property (nonatomic, strong) NSArray *divorceFileds;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of divorceFileds
@property (nonatomic, strong) NSMutableArray *mutableDivorceFileds;

/// @name Accessing family events 

///Also contained in familyEvents. . GCEngagementAttribute
@property (nonatomic, strong) NSArray *engagements;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of engagements
@property (nonatomic, strong) NSMutableArray *mutableEngagements;

/// @name Accessing family events 

///Also contained in familyEvents. . GCMarriageAttribute
@property (nonatomic, strong) NSArray *marriages;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of marriages
@property (nonatomic, strong) NSMutableArray *mutableMarriages;

/// @name Accessing family events 

///Also contained in familyEvents. . GCMarriageBannAttribute
@property (nonatomic, strong) NSArray *marriageBanns;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of marriageBanns
@property (nonatomic, strong) NSMutableArray *mutableMarriageBanns;

/// @name Accessing family events 

///Also contained in familyEvents. . GCMarriageContractAttribute
@property (nonatomic, strong) NSArray *marriageContracts;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of marriageContracts
@property (nonatomic, strong) NSMutableArray *mutableMarriageContracts;

/// @name Accessing family events 

///Also contained in familyEvents. . GCMarriageLicenseAttribute
@property (nonatomic, strong) NSArray *marriageLicenses;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of marriageLicenses
@property (nonatomic, strong) NSMutableArray *mutableMarriageLicenses;

/// @name Accessing family events 

///Also contained in familyEvents. . GCMarriageSettlementAttribute
@property (nonatomic, strong) NSArray *marriageSettlements;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of marriageSettlements
@property (nonatomic, strong) NSMutableArray *mutableMarriageSettlements;

/// @name Accessing family events 

///Also contained in familyEvents. . GCGenericEventAttribute
@property (nonatomic, strong) NSArray *genericEvents;
/// @name Accessing family events 

///Also contained in familyEvents. . Contains instances of genericEvents
@property (nonatomic, strong) NSMutableArray *mutableGenericEvents;

/// . 
@property (nonatomic, strong) GCHusbandRelationship *husband;

/// . 
@property (nonatomic, strong) GCWifeRelationship *wife;

/// . GCChildRelationship
@property (nonatomic, strong) NSArray *children;
/// . Contains instances of children
@property (nonatomic, strong) NSMutableArray *mutableChildren;

/// . 
@property (nonatomic, strong) GCNumberOfChildrenAttribute *numberOfChildren;

/// . GCSubmitterReferenceRelationship
@property (nonatomic, strong) NSArray *submitterReferences;
/// . Contains instances of submitterReferences
@property (nonatomic, strong) NSMutableArray *mutableSubmitterReferences;

/// . GCLDSSealingSpouseAttribute
@property (nonatomic, strong) NSArray *lDSSealingSpouses;
/// . Contains instances of lDSSealingSpouses
@property (nonatomic, strong) NSMutableArray *mutableLDSSealingSpouses;

/// @name Accessing sources

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *sources;

/// @name Accessing sources 

///Also contained in sources. . GCSourceCitationRelationship
@property (nonatomic, strong) NSArray *sourceCitations;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceCitations
@property (nonatomic, strong) NSMutableArray *mutableSourceCitations;

/// @name Accessing sources 

///Also contained in sources. . GCSourceEmbeddedAttribute
@property (nonatomic, strong) NSArray *sourceEmbeddeds;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableSourceEmbeddeds;

/// @name Accessing multimedias

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *multimedias;

/// @name Accessing multimedias 

///Also contained in multimedias. . GCMultimediaReferenceRelationship
@property (nonatomic, strong) NSArray *multimediaReferences;
/// @name Accessing multimedias 

///Also contained in multimedias. . Contains instances of multimediaReferences
@property (nonatomic, strong) NSMutableArray *mutableMultimediaReferences;

/// @name Accessing multimedias 

///Also contained in multimedias. . GCMultimediaEmbeddedAttribute
@property (nonatomic, strong) NSArray *multimediaEmbeddeds;
/// @name Accessing multimedias 

///Also contained in multimedias. . Contains instances of multimediaEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableMultimediaEmbeddeds;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;

/// . GCUserReferenceNumberAttribute
@property (nonatomic, strong) NSArray *userReferenceNumbers;
/// . Contains instances of userReferenceNumbers
@property (nonatomic, strong) NSMutableArray *mutableUserReferenceNumbers;

/// . 
@property (nonatomic, strong) GCRecordIdNumberAttribute *recordIdNumber;

/// . 
@property (nonatomic, strong) GCChangeInfoAttribute *changeInfo;


@end
