/*
 This file was autogenerated by tags.py 
 */

#import "GCEntity.h"

@class GCCharacterSetAttribute;
@class GCCopyrightAttribute;
@class GCDestinationAttribute;
@class GCFileAttribute;
@class GCGedcomAttribute;
@class GCHeaderDateAttribute;
@class GCHeaderSourceAttribute;
@class GCLanguageAttribute;
@class GCNoteEmbeddedAttribute;
@class GCPlaceFormatSpecifierAttribute;
@class GCSubmissionReferenceRelationship;
@class GCSubmitterReferenceRelationship;

/**
 The header structure provides information about the entire transmission. The headerSource identifies which system sent the data. The destination identifies the intended receiving system.
*/
@interface GCHeaderEntity : GCEntity

// Methods:
/// @name Initializing

/** Initializes and returns a header.

 @param context The context in which to create the entity.
 @return A new header.
*/
+(instancetype)headerInContext:(GCContext *)context;

// Properties:
/// .  NB: required property.
@property (nonatomic, strong) GCHeaderSourceAttribute *headerSource;

/// . GCDestinationAttribute
@property (nonatomic, strong) NSArray *destinations;
/// . Contains instances of destinations
@property (nonatomic, strong) NSMutableArray *mutableDestinations;

/// . 
@property (nonatomic, strong) GCHeaderDateAttribute *headerDate;

/// .  NB: required property.
@property (nonatomic, strong) GCSubmitterReferenceRelationship *submitterReference;

/// . GCSubmissionReferenceRelationship
@property (nonatomic, strong) NSArray *submissionReferences;
/// . Contains instances of submissionReferences
@property (nonatomic, strong) NSMutableArray *mutableSubmissionReferences;

/// . 
@property (nonatomic, strong) GCFileAttribute *file;

/// . 
@property (nonatomic, strong) GCCopyrightAttribute *copyright;

/// .  NB: required property.
@property (nonatomic, strong) GCGedcomAttribute *gedcom;

/// .  NB: required property.
@property (nonatomic, strong) GCCharacterSetAttribute *characterSet;

/// . 
@property (nonatomic, strong) GCLanguageAttribute *language;

/// . 
@property (nonatomic, strong) GCPlaceFormatSpecifierAttribute *placeFormatSpecifier;

/// . 
@property (nonatomic, strong) GCNoteEmbeddedAttribute *noteEmbedded;


@end
