/*
 This file was autogenerated by tags.py 
 */

#import "GCRecord.h"

@class GCAdoptionAttribute;
@class GCAdultChristeningAttribute;
@class GCAliasRelationship;
@class GCAncestorInterestRelationship;
@class GCAncestralFileNumberAttribute;
@class GCAssociationRelationship;
@class GCBaptismAttribute;
@class GCBarMitzvahAttribute;
@class GCBasMitzvahAttribute;
@class GCBirthAttribute;
@class GCBlessingAttribute;
@class GCBurialAttribute;
@class GCCasteAttribute;
@class GCCensusAttribute;
@class GCChangeInfoAttribute;
@class GCChildInFamilyRelationship;
@class GCChristeningAttribute;
@class GCConfirmationAttribute;
@class GCCremationAttribute;
@class GCDeathAttribute;
@class GCDescendantInterestRelationship;
@class GCEducationAttribute;
@class GCEmigrationAttribute;
@class GCFirstCommunionAttribute;
@class GCGenerationsOfDescendantsAttribute;
@class GCGenericEventAttribute;
@class GCGraduationAttribute;
@class GCIdentNumberAttribute;
@class GCImmigrationAttribute;
@class GCLDSBaptismAttribute;
@class GCLDSConfirmationAttribute;
@class GCLDSEndowmentAttribute;
@class GCLDSSealingChildAttribute;
@class GCMultimediaEmbeddedAttribute;
@class GCMultimediaReferenceRelationship;
@class GCNationalityAttribute;
@class GCNaturalizationAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCNumberOfChildrenAttribute;
@class GCNumberOfMarriagesAttribute;
@class GCOccupationAttribute;
@class GCOrdinationAttribute;
@class GCPersonalNameAttribute;
@class GCPhysicalDescriptionAttribute;
@class GCProbateAttribute;
@class GCPropertyOwnedAttribute;
@class GCRecordFileNumberAttribute;
@class GCRecordIdNumberAttribute;
@class GCReligionAttribute;
@class GCResidenceAttribute;
@class GCRestrictionNoticeAttribute;
@class GCRetirementAttribute;
@class GCSexAttribute;
@class GCSocialSecurityNumberAttribute;
@class GCSourceCitationRelationship;
@class GCSourceEmbeddedAttribute;
@class GCSpouseInFamilyRelationship;
@class GCSubmitterReferenceRelationship;
@class GCTitleAttribute;
@class GCUserReferenceNumberAttribute;
@class GCWillAttribute;

/**
 The individual record is a compilation of facts, known or discovered, about an individual. Sometimes these facts are from different sources. This form allows documentation of the source where each of the facts were discovered.
*/
@interface GCIndividualRecord : GCRecord

// Methods:
/// @name Initializing

/** Initializes and returns a individual.

 @param context The context in which to create the entity.
 @return A new individual.
*/
+(instancetype)individualInContext:(GCContext *)context;

// Properties:
/// . 
@property (nonatomic, strong) GCRestrictionNoticeAttribute *restrictionNotice;

/// . GCPersonalNameAttribute
@property (nonatomic, strong) NSArray *personalNames;
/// . Contains instances of personalNames
@property (nonatomic, strong) NSMutableArray *mutablePersonalNames;

/// . 
@property (nonatomic, strong) GCSexAttribute *sex;

/// @name Accessing individual events

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *individualEvents;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCBirthAttribute
@property (nonatomic, strong) NSArray *births;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of births
@property (nonatomic, strong) NSMutableArray *mutableBirths;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCChristeningAttribute
@property (nonatomic, strong) NSArray *christenings;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of christenings
@property (nonatomic, strong) NSMutableArray *mutableChristenings;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCDeathAttribute
@property (nonatomic, strong) NSArray *deaths;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of deaths
@property (nonatomic, strong) NSMutableArray *mutableDeaths;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCBurialAttribute
@property (nonatomic, strong) NSArray *burials;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of burials
@property (nonatomic, strong) NSMutableArray *mutableBurials;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCCremationAttribute
@property (nonatomic, strong) NSArray *cremations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of cremations
@property (nonatomic, strong) NSMutableArray *mutableCremations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCAdoptionAttribute
@property (nonatomic, strong) NSArray *adoptions;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of adoptions
@property (nonatomic, strong) NSMutableArray *mutableAdoptions;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCBaptismAttribute
@property (nonatomic, strong) NSArray *baptisms;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of baptisms
@property (nonatomic, strong) NSMutableArray *mutableBaptisms;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCBarMitzvahAttribute
@property (nonatomic, strong) NSArray *barMitzvahs;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of barMitzvahs
@property (nonatomic, strong) NSMutableArray *mutableBarMitzvahs;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCBasMitzvahAttribute
@property (nonatomic, strong) NSArray *basMitzvahs;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of basMitzvahs
@property (nonatomic, strong) NSMutableArray *mutableBasMitzvahs;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCBlessingAttribute
@property (nonatomic, strong) NSArray *blessings;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of blessings
@property (nonatomic, strong) NSMutableArray *mutableBlessings;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCAdultChristeningAttribute
@property (nonatomic, strong) NSArray *adultChristenings;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of adultChristenings
@property (nonatomic, strong) NSMutableArray *mutableAdultChristenings;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCConfirmationAttribute
@property (nonatomic, strong) NSArray *confirmations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of confirmations
@property (nonatomic, strong) NSMutableArray *mutableConfirmations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCFirstCommunionAttribute
@property (nonatomic, strong) NSArray *firstCommunions;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of firstCommunions
@property (nonatomic, strong) NSMutableArray *mutableFirstCommunions;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCOrdinationAttribute
@property (nonatomic, strong) NSArray *ordinations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of ordinations
@property (nonatomic, strong) NSMutableArray *mutableOrdinations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCNaturalizationAttribute
@property (nonatomic, strong) NSArray *naturalizations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of naturalizations
@property (nonatomic, strong) NSMutableArray *mutableNaturalizations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCEmigrationAttribute
@property (nonatomic, strong) NSArray *emigrations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of emigrations
@property (nonatomic, strong) NSMutableArray *mutableEmigrations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCImmigrationAttribute
@property (nonatomic, strong) NSArray *immigrations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of immigrations
@property (nonatomic, strong) NSMutableArray *mutableImmigrations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCCensusAttribute
@property (nonatomic, strong) NSArray *censuses;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of censuses
@property (nonatomic, strong) NSMutableArray *mutableCensuses;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCProbateAttribute
@property (nonatomic, strong) NSArray *probates;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of probates
@property (nonatomic, strong) NSMutableArray *mutableProbates;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCWillAttribute
@property (nonatomic, strong) NSArray *wills;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of wills
@property (nonatomic, strong) NSMutableArray *mutableWills;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCGraduationAttribute
@property (nonatomic, strong) NSArray *graduations;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of graduations
@property (nonatomic, strong) NSMutableArray *mutableGraduations;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCRetirementAttribute
@property (nonatomic, strong) NSArray *retirements;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of retirements
@property (nonatomic, strong) NSMutableArray *mutableRetirements;

/// @name Accessing individual events 

///Also contained in individualEvents. . GCGenericEventAttribute
@property (nonatomic, strong) NSArray *genericEvents;
/// @name Accessing individual events 

///Also contained in individualEvents. . Contains instances of genericEvents
@property (nonatomic, strong) NSMutableArray *mutableGenericEvents;

/// @name Accessing individual attributes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *individualAttributes;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCCasteAttribute
@property (nonatomic, strong) NSArray *castes;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of castes
@property (nonatomic, strong) NSMutableArray *mutableCastes;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCPhysicalDescriptionAttribute
@property (nonatomic, strong) NSArray *physicalDescriptions;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of physicalDescriptions
@property (nonatomic, strong) NSMutableArray *mutablePhysicalDescriptions;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCGenerationsOfDescendantsAttribute
@property (nonatomic, strong) NSArray *generationsOfDescendantss;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of generationsOfDescendantss
@property (nonatomic, strong) NSMutableArray *mutableGenerationsOfDescendantss;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCEducationAttribute
@property (nonatomic, strong) NSArray *educations;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of educations
@property (nonatomic, strong) NSMutableArray *mutableEducations;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCIdentNumberAttribute
@property (nonatomic, strong) NSArray *identNumbers;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of identNumbers
@property (nonatomic, strong) NSMutableArray *mutableIdentNumbers;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCNationalityAttribute
@property (nonatomic, strong) NSArray *nationalities;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of nationalities
@property (nonatomic, strong) NSMutableArray *mutableNationalities;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCNumberOfChildrenAttribute
@property (nonatomic, strong) NSArray *numberOfChildrens;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of numberOfChildrens
@property (nonatomic, strong) NSMutableArray *mutableNumberOfChildrens;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCNumberOfMarriagesAttribute
@property (nonatomic, strong) NSArray *numberOfMarriagess;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of numberOfMarriagess
@property (nonatomic, strong) NSMutableArray *mutableNumberOfMarriagess;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCOccupationAttribute
@property (nonatomic, strong) NSArray *occupations;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of occupations
@property (nonatomic, strong) NSMutableArray *mutableOccupations;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCPropertyOwnedAttribute
@property (nonatomic, strong) NSArray *propertyOwneds;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of propertyOwneds
@property (nonatomic, strong) NSMutableArray *mutablePropertyOwneds;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCReligionAttribute
@property (nonatomic, strong) NSArray *religions;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of religions
@property (nonatomic, strong) NSMutableArray *mutableReligions;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCResidenceAttribute
@property (nonatomic, strong) NSArray *residences;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of residences
@property (nonatomic, strong) NSMutableArray *mutableResidences;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCSocialSecurityNumberAttribute
@property (nonatomic, strong) NSArray *socialSecurityNumbers;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of socialSecurityNumbers
@property (nonatomic, strong) NSMutableArray *mutableSocialSecurityNumbers;

/// @name Accessing individual attributes 

///Also contained in individualAttributes. . GCTitleAttribute
@property (nonatomic, strong) NSArray *titles;
/// @name Accessing individual attributes 

///Also contained in individualAttributes. . Contains instances of titles
@property (nonatomic, strong) NSMutableArray *mutableTitles;

/// @name Accessing individual lds ordinances

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *individualLDSOrdinances;

/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . GCLDSBaptismAttribute
@property (nonatomic, strong) NSArray *lDSBaptisms;
/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . Contains instances of lDSBaptisms
@property (nonatomic, strong) NSMutableArray *mutableLDSBaptisms;

/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . GCLDSConfirmationAttribute
@property (nonatomic, strong) NSArray *lDSConfirmations;
/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . Contains instances of lDSConfirmations
@property (nonatomic, strong) NSMutableArray *mutableLDSConfirmations;

/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . GCLDSEndowmentAttribute
@property (nonatomic, strong) NSArray *lDSEndowments;
/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . Contains instances of lDSEndowments
@property (nonatomic, strong) NSMutableArray *mutableLDSEndowments;

/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . GCLDSSealingChildAttribute
@property (nonatomic, strong) NSArray *lDSSealingChilds;
/// @name Accessing individual lds ordinances 

///Also contained in individualLDSOrdinances. . Contains instances of lDSSealingChilds
@property (nonatomic, strong) NSMutableArray *mutableLDSSealingChilds;

/// . GCChildInFamilyRelationship
@property (nonatomic, strong) NSArray *childInFamilies;
/// . Contains instances of childInFamilies
@property (nonatomic, strong) NSMutableArray *mutableChildInFamilies;

/// . GCSpouseInFamilyRelationship
@property (nonatomic, strong) NSArray *spouseInFamilies;
/// . Contains instances of spouseInFamilies
@property (nonatomic, strong) NSMutableArray *mutableSpouseInFamilies;

/// . GCSubmitterReferenceRelationship
@property (nonatomic, strong) NSArray *submitterReferences;
/// . Contains instances of submitterReferences
@property (nonatomic, strong) NSMutableArray *mutableSubmitterReferences;

/// . GCAssociationRelationship
@property (nonatomic, strong) NSArray *associations;
/// . Contains instances of associations
@property (nonatomic, strong) NSMutableArray *mutableAssociations;

/// . GCAliasRelationship
@property (nonatomic, strong) NSArray *aliases;
/// . Contains instances of aliases
@property (nonatomic, strong) NSMutableArray *mutableAliases;

/// . GCAncestorInterestRelationship
@property (nonatomic, strong) NSArray *ancestorInterests;
/// . Contains instances of ancestorInterests
@property (nonatomic, strong) NSMutableArray *mutableAncestorInterests;

/// . GCDescendantInterestRelationship
@property (nonatomic, strong) NSArray *descendantInterests;
/// . Contains instances of descendantInterests
@property (nonatomic, strong) NSMutableArray *mutableDescendantInterests;

/// @name Accessing sources

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *sources;

/// @name Accessing sources 

///Also contained in sources. . GCSourceCitationRelationship
@property (nonatomic, strong) NSArray *sourceCitations;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceCitations
@property (nonatomic, strong) NSMutableArray *mutableSourceCitations;

/// @name Accessing sources 

///Also contained in sources. . GCSourceEmbeddedAttribute
@property (nonatomic, strong) NSArray *sourceEmbeddeds;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableSourceEmbeddeds;

/// @name Accessing multimedias

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *multimedias;

/// @name Accessing multimedias 

///Also contained in multimedias. . GCMultimediaReferenceRelationship
@property (nonatomic, strong) NSArray *multimediaReferences;
/// @name Accessing multimedias 

///Also contained in multimedias. . Contains instances of multimediaReferences
@property (nonatomic, strong) NSMutableArray *mutableMultimediaReferences;

/// @name Accessing multimedias 

///Also contained in multimedias. . GCMultimediaEmbeddedAttribute
@property (nonatomic, strong) NSArray *multimediaEmbeddeds;
/// @name Accessing multimedias 

///Also contained in multimedias. . Contains instances of multimediaEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableMultimediaEmbeddeds;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;

/// . GCRecordFileNumberAttribute
@property (nonatomic, strong) NSArray *recordFileNumbers;
/// . Contains instances of recordFileNumbers
@property (nonatomic, strong) NSMutableArray *mutableRecordFileNumbers;

/// . GCAncestralFileNumberAttribute
@property (nonatomic, strong) NSArray *ancestralFileNumbers;
/// . Contains instances of ancestralFileNumbers
@property (nonatomic, strong) NSMutableArray *mutableAncestralFileNumbers;

/// . GCUserReferenceNumberAttribute
@property (nonatomic, strong) NSArray *userReferenceNumbers;
/// . Contains instances of userReferenceNumbers
@property (nonatomic, strong) NSMutableArray *mutableUserReferenceNumbers;

/// . 
@property (nonatomic, strong) GCRecordIdNumberAttribute *recordIdNumber;

/// . 
@property (nonatomic, strong) GCChangeInfoAttribute *changeInfo;


@end
