/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCLatitudeAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a latitude.

 
 @return A new latitude.
*/
+(instancetype)latitude;
/// @name Initializing

/** Initializes and returns a latitude.

 @param value The value as a GCValue object.
 @return A new latitude.
*/
+(instancetype)latitudeWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a latitude.

 @param value The value as an NSString.
 @return A new latitude.
*/
+(instancetype)latitudeWithGedcomStringValue:(NSString *)value;

// Properties:


@end
