/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCLongitudeAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a longitude.

 
 @return A new longitude.
*/
+(instancetype)longitude;
/// @name Initializing

/** Initializes and returns a longitude.

 @param value The value as a GCValue object.
 @return A new longitude.
*/
+(instancetype)longitudeWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a longitude.

 @param value The value as an NSString.
 @return A new longitude.
*/
+(instancetype)longitudeWithGedcomStringValue:(NSString *)value;

// Properties:


@end
