/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"

@class GCLatitudeAttribute;
@class GCLongitudeAttribute;

/**
 
*/
@interface GCMapAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a map.

 
 @return A new map.
*/
+(instancetype)map;
/// @name Initializing

/** Initializes and returns a map.

 @param value The value as a GCValue object.
 @return A new map.
*/
+(instancetype)mapWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a map.

 @param value The value as an NSString.
 @return A new map.
*/
+(instancetype)mapWithGedcomStringValue:(NSString *)value;

// Properties:
/// .  NB: required property.
@property (nonatomic, strong) GCLongitudeAttribute *longitude;

/// .  NB: required property.
@property (nonatomic, strong) GCLatitudeAttribute *latitude;


@end
