/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"

@class GCFileAttribute;
@class GCMultimediaFormatAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCTitleAttribute;

/**
 
*/
@interface GCMultimediaEmbeddedAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a multimediaEmbedded.

 
 @return A new multimediaEmbedded.
*/
+(instancetype)multimediaEmbedded;
/// @name Initializing

/** Initializes and returns a multimediaEmbedded.

 @param value The value as a GCValue object.
 @return A new multimediaEmbedded.
*/
+(instancetype)multimediaEmbeddedWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a multimediaEmbedded.

 @param value The value as an NSString.
 @return A new multimediaEmbedded.
*/
+(instancetype)multimediaEmbeddedWithGedcomStringValue:(NSString *)value;

// Properties:
/// .  NB: required property.
@property (nonatomic, strong) GCMultimediaFormatAttribute *multimediaFormat;

/// . 
@property (nonatomic, strong) GCTitleAttribute *title;

/// . 
@property (nonatomic, strong) GCFileAttribute *file;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;


@end
