/*
 This file was autogenerated by tags.py 
 */

#import "GCRecord.h"

@class GCBinaryObjectAttribute;
@class GCChangeInfoAttribute;
@class GCFileAttribute;
@class GCMultimediaFormatAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCRecordIdNumberAttribute;
@class GCTitleAttribute;
@class GCUserReferenceNumberAttribute;

/**
 
*/
@interface GCMultimediaRecord : GCRecord

// Methods:
/// @name Initializing

/** Initializes and returns a multimedia.

 @param context The context in which to create the entity.
 @return A new multimedia.
*/
+(instancetype)multimediaInContext:(GCContext *)context;

// Properties:
/// .  NB: required property.
@property (nonatomic, strong) GCMultimediaFormatAttribute *multimediaFormat;

/// . 
@property (nonatomic, strong) GCTitleAttribute *title;

/// . 
@property (nonatomic, strong) GCFileAttribute *file;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;

/// . 
@property (nonatomic, strong) GCBinaryObjectAttribute *binaryObject;

/// . GCUserReferenceNumberAttribute
@property (nonatomic, strong) NSArray *userReferenceNumbers;
/// . Contains instances of userReferenceNumbers
@property (nonatomic, strong) NSMutableArray *mutableUserReferenceNumbers;

/// . 
@property (nonatomic, strong) GCRecordIdNumberAttribute *recordIdNumber;

/// . 
@property (nonatomic, strong) GCChangeInfoAttribute *changeInfo;


@end
