/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"

@class GCGivenNameAttribute;
@class GCNamePrefixAttribute;
@class GCNameSuffixAttribute;
@class GCNicknameAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCSecondGenerationNameAttribute;
@class GCSourceCitationRelationship;
@class GCSourceEmbeddedAttribute;
@class GCSurnameAttribute;
@class GCSurnamePrefixAttribute;

/**
 
*/
@interface GCPersonalNameAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a personalName.

 
 @return A new personalName.
*/
+(instancetype)personalName;
/// @name Initializing

/** Initializes and returns a personalName.

 @param value The value as a GCValue object.
 @return A new personalName.
*/
+(instancetype)personalNameWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a personalName.

 @param value The value as an NSString.
 @return A new personalName.
*/
+(instancetype)personalNameWithGedcomStringValue:(NSString *)value;

// Properties:
/// . 
@property (nonatomic, strong) GCNamePrefixAttribute *namePrefix;

/// . 
@property (nonatomic, strong) GCGivenNameAttribute *givenName;

/// . 
@property (nonatomic, strong) GCNicknameAttribute *nickname;

/// . 
@property (nonatomic, strong) GCSurnamePrefixAttribute *surnamePrefix;

/// . 
@property (nonatomic, strong) GCSurnameAttribute *surname;

/// . 
@property (nonatomic, strong) GCNameSuffixAttribute *nameSuffix;

/// . 
@property (nonatomic, strong) GCSecondGenerationNameAttribute *secondGenerationName;

/// @name Accessing sources

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *sources;

/// @name Accessing sources 

///Also contained in sources. . GCSourceCitationRelationship
@property (nonatomic, strong) NSArray *sourceCitations;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceCitations
@property (nonatomic, strong) NSMutableArray *mutableSourceCitations;

/// @name Accessing sources 

///Also contained in sources. . GCSourceEmbeddedAttribute
@property (nonatomic, strong) NSArray *sourceEmbeddeds;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableSourceEmbeddeds;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;


@end
