/*
 This file was autogenerated by tags.py 
 */

#import "GCEventDetailAttribute.h"

@class GCMapAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCPlaceFormatAttribute;
@class GCSourceCitationRelationship;
@class GCSourceEmbeddedAttribute;

/**
 
*/
@interface GCPlaceAttribute : GCEventDetailAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a place.

 
 @return A new place.
*/
+(instancetype)place;
/// @name Initializing

/** Initializes and returns a place.

 @param value The value as a GCValue object.
 @return A new place.
*/
+(instancetype)placeWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a place.

 @param value The value as an NSString.
 @return A new place.
*/
+(instancetype)placeWithGedcomStringValue:(NSString *)value;

// Properties:
/// . 
@property (nonatomic, strong) GCPlaceFormatAttribute *placeFormat;

/// . 
@property (nonatomic, strong) GCMapAttribute *map;

/// @name Accessing sources

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *sources;

/// @name Accessing sources 

///Also contained in sources. . GCSourceCitationRelationship
@property (nonatomic, strong) NSArray *sourceCitations;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceCitations
@property (nonatomic, strong) NSMutableArray *mutableSourceCitations;

/// @name Accessing sources 

///Also contained in sources. . GCSourceEmbeddedAttribute
@property (nonatomic, strong) NSArray *sourceEmbeddeds;
/// @name Accessing sources 

///Also contained in sources. . Contains instances of sourceEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableSourceEmbeddeds;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;


@end
