/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCSecondGenerationNameAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a secondGenerationName.

 
 @return A new secondGenerationName.
*/
+(instancetype)secondGenerationName;
/// @name Initializing

/** Initializes and returns a secondGenerationName.

 @param value The value as a GCValue object.
 @return A new secondGenerationName.
*/
+(instancetype)secondGenerationNameWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a secondGenerationName.

 @param value The value as an NSString.
 @return A new secondGenerationName.
*/
+(instancetype)secondGenerationNameWithGedcomStringValue:(NSString *)value;

// Properties:


@end
