/*
 This file was autogenerated by tags.py 
 */

#import "GCRecord.h"

@class GCAbbreviationAttribute;
@class GCAuthorAttribute;
@class GCChangeInfoAttribute;
@class GCMultimediaEmbeddedAttribute;
@class GCMultimediaReferenceRelationship;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCPublicationFactsAttribute;
@class GCRecordIdNumberAttribute;
@class GCRepositoryCitationRelationship;
@class GCSourceDataAttribute;
@class GCTextAttribute;
@class GCTitleAttribute;
@class GCUserReferenceNumberAttribute;

/**
 Source records are used to provide a bibliographic description of the source cited.
*/
@interface GCSourceRecord : GCRecord

// Methods:
/// @name Initializing

/** Initializes and returns a source.

 @param context The context in which to create the entity.
 @return A new source.
*/
+(instancetype)sourceInContext:(GCContext *)context;

// Properties:
/// . 
@property (nonatomic, strong) GCSourceDataAttribute *sourceData;

/// . 
@property (nonatomic, strong) GCAuthorAttribute *author;

/// . 
@property (nonatomic, strong) GCTitleAttribute *title;

/// . 
@property (nonatomic, strong) GCAbbreviationAttribute *abbreviation;

/// . 
@property (nonatomic, strong) GCPublicationFactsAttribute *publicationFacts;

/// . 
@property (nonatomic, strong) GCTextAttribute *text;

/// . 
@property (nonatomic, strong) GCRepositoryCitationRelationship *repositoryCitation;

/// @name Accessing multimedias

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *multimedias;

/// @name Accessing multimedias 

///Also contained in multimedias. . GCMultimediaReferenceRelationship
@property (nonatomic, strong) NSArray *multimediaReferences;
/// @name Accessing multimedias 

///Also contained in multimedias. . Contains instances of multimediaReferences
@property (nonatomic, strong) NSMutableArray *mutableMultimediaReferences;

/// @name Accessing multimedias 

///Also contained in multimedias. . GCMultimediaEmbeddedAttribute
@property (nonatomic, strong) NSArray *multimediaEmbeddeds;
/// @name Accessing multimedias 

///Also contained in multimedias. . Contains instances of multimediaEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableMultimediaEmbeddeds;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic, strong) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic, strong) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic, strong) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic, strong) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic, strong) NSMutableArray *mutableNoteEmbeddeds;

/// . 
@property (nonatomic, strong) GCUserReferenceNumberAttribute *userReferenceNumber;

/// . 
@property (nonatomic, strong) GCRecordIdNumberAttribute *recordIdNumber;

/// . 
@property (nonatomic, strong) GCChangeInfoAttribute *changeInfo;


@end
