/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCWebAddressAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a webAddress.

 
 @return A new webAddress.
*/
+(instancetype)webAddress;
/// @name Initializing

/** Initializes and returns a webAddress.

 @param value The value as a GCValue object.
 @return A new webAddress.
*/
+(instancetype)webAddressWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a webAddress.

 @param value The value as an NSString.
 @return A new webAddress.
*/
+(instancetype)webAddressWithGedcomStringValue:(NSString *)value;

// Properties:


@end
