/*
 This file was autogenerated by tags.py 
 */

#import "GCAddressStructureAttribute.h"

@implementation GCAddressStructureAttribute {

}

// Methods:
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
