/*
 This file was autogenerated by tags.py 
 */

#import "GCCorporationAttribute.h"

@implementation GCCorporationAttribute {
	GCAddressAttribute *_address;
	NSMutableArray *_phoneNumbers;
	NSMutableArray *_emailAddresses;
	NSMutableArray *_faxNumbers;
	NSMutableArray *_webAddresses;
}

// Methods:
/// @name Initializing

/** Initializes and returns a corporation.

 
 @return A new corporation.
*/
+(instancetype)corporation
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a corporation.

 @param value The value as a GCValue object.
 @return A new corporation.
*/
+(instancetype)corporationWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a corporation.

 @param value The value as an NSString.
 @return A new corporation.
*/
+(instancetype)corporationWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:
		_phoneNumbers = [NSMutableArray array];
		_emailAddresses = [NSMutableArray array];
		_faxNumbers = [NSMutableArray array];
		_webAddresses = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic addressStructures;
@dynamic address;
@synthesize phoneNumbers = _phoneNumbers;
@dynamic mutablePhoneNumbers;
- (NSMutableArray *)mutablePhoneNumbers
{
	return [self mutableArrayValueForKey:@"phoneNumbers"];
}

@synthesize emailAddresses = _emailAddresses;
@dynamic mutableEmailAddresses;
- (NSMutableArray *)mutableEmailAddresses
{
	return [self mutableArrayValueForKey:@"emailAddresses"];
}

@synthesize faxNumbers = _faxNumbers;
@dynamic mutableFaxNumbers;
- (NSMutableArray *)mutableFaxNumbers
{
	return [self mutableArrayValueForKey:@"faxNumbers"];
}

@synthesize webAddresses = _webAddresses;
@dynamic mutableWebAddresses;
- (NSMutableArray *)mutableWebAddresses
{
	return [self mutableArrayValueForKey:@"webAddresses"];
}


@end
