/*
 This file was autogenerated by tags.py 
 */

#import "GCEmailAddressAttribute.h"

@implementation GCEmailAddressAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a emailAddress.

 
 @return A new emailAddress.
*/
+(instancetype)emailAddress
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a emailAddress.

 @param value The value as a GCValue object.
 @return A new emailAddress.
*/
+(instancetype)emailAddressWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a emailAddress.

 @param value The value as an NSString.
 @return A new emailAddress.
*/
+(instancetype)emailAddressWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
