/*
 This file was autogenerated by tags.py 
 */

#import "GCFaxNumberAttribute.h"

@implementation GCFaxNumberAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a faxNumber.

 
 @return A new faxNumber.
*/
+(instancetype)faxNumber
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a faxNumber.

 @param value The value as a GCValue object.
 @return A new faxNumber.
*/
+(instancetype)faxNumberWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a faxNumber.

 @param value The value as an NSString.
 @return A new faxNumber.
*/
+(instancetype)faxNumberWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
