/*
 This file was autogenerated by tags.py 
 */

#import "GCLatitudeAttribute.h"

@implementation GCLatitudeAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a latitude.

 
 @return A new latitude.
*/
+(instancetype)latitude
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a latitude.

 @param value The value as a GCValue object.
 @return A new latitude.
*/
+(instancetype)latitudeWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a latitude.

 @param value The value as an NSString.
 @return A new latitude.
*/
+(instancetype)latitudeWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
