/*
 This file was autogenerated by tags.py 
 */

#import "GCLongitudeAttribute.h"

@implementation GCLongitudeAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a longitude.

 
 @return A new longitude.
*/
+(instancetype)longitude
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a longitude.

 @param value The value as a GCValue object.
 @return A new longitude.
*/
+(instancetype)longitudeWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a longitude.

 @param value The value as an NSString.
 @return A new longitude.
*/
+(instancetype)longitudeWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
