/*
 This file was autogenerated by tags.py 
 */

#import "GCMapAttribute.h"

@implementation GCMapAttribute {
	GCLongitudeAttribute *_longitude;
	GCLatitudeAttribute *_latitude;
}

// Methods:
/// @name Initializing

/** Initializes and returns a map.

 
 @return A new map.
*/
+(instancetype)map
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a map.

 @param value The value as a GCValue object.
 @return A new map.
*/
+(instancetype)mapWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a map.

 @param value The value as an NSString.
 @return A new map.
*/
+(instancetype)mapWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic longitude;
@dynamic latitude;

@end
