/*
 This file was autogenerated by tags.py 
 */

#import "GCSecondGenerationNameAttribute.h"

@implementation GCSecondGenerationNameAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a secondGenerationName.

 
 @return A new secondGenerationName.
*/
+(instancetype)secondGenerationName
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a secondGenerationName.

 @param value The value as a GCValue object.
 @return A new secondGenerationName.
*/
+(instancetype)secondGenerationNameWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a secondGenerationName.

 @param value The value as an NSString.
 @return A new secondGenerationName.
*/
+(instancetype)secondGenerationNameWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
