/*
 This file was autogenerated by tags.py 
 */

#import "GCSubmitterRecord.h"

@implementation GCSubmitterRecord {
	GCDescriptiveNameAttribute *_descriptiveName;
	GCAddressAttribute *_address;
	NSMutableArray *_phoneNumbers;
	NSMutableArray *_emailAddresses;
	NSMutableArray *_faxNumbers;
	NSMutableArray *_webAddresses;
	NSMutableArray *_multimediaReferences;
	NSMutableArray *_multimediaEmbeddeds;
	NSMutableArray *_languages;
	GCRecordFileNumberAttribute *_recordFileNumber;
	GCAncestralFileNumberAttribute *_ancestralFileNumber;
	NSMutableArray *_userReferenceNumbers;
	GCRecordIdNumberAttribute *_recordIdNumber;
	GCChangeInfoAttribute *_changeInfo;
}

// Methods:
/// @name Initializing

/** Initializes and returns a submitter.

 @param context The context in which to create the entity.
 @return A new submitter.
*/
+(instancetype)submitterInContext:(GCContext *)context
{
	return [[self alloc] initInContext:context];
}
- (instancetype)initInContext:(GCContext *)context
{
	self = [super initInContext:context];
	
	if (self) {
		// initialize ivars, if any:
		_phoneNumbers = [NSMutableArray array];
		_emailAddresses = [NSMutableArray array];
		_faxNumbers = [NSMutableArray array];
		_webAddresses = [NSMutableArray array];
		_multimediaReferences = [NSMutableArray array];
		_multimediaEmbeddeds = [NSMutableArray array];
		_languages = [NSMutableArray array];
		_userReferenceNumbers = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic descriptiveName;
@dynamic addressStructures;
@dynamic address;
@synthesize phoneNumbers = _phoneNumbers;
@dynamic mutablePhoneNumbers;
- (NSMutableArray *)mutablePhoneNumbers
{
	return [self mutableArrayValueForKey:@"phoneNumbers"];
}

@synthesize emailAddresses = _emailAddresses;
@dynamic mutableEmailAddresses;
- (NSMutableArray *)mutableEmailAddresses
{
	return [self mutableArrayValueForKey:@"emailAddresses"];
}

@synthesize faxNumbers = _faxNumbers;
@dynamic mutableFaxNumbers;
- (NSMutableArray *)mutableFaxNumbers
{
	return [self mutableArrayValueForKey:@"faxNumbers"];
}

@synthesize webAddresses = _webAddresses;
@dynamic mutableWebAddresses;
- (NSMutableArray *)mutableWebAddresses
{
	return [self mutableArrayValueForKey:@"webAddresses"];
}

@dynamic multimedias;
@synthesize multimediaReferences = _multimediaReferences;
@dynamic mutableMultimediaReferences;
- (NSMutableArray *)mutableMultimediaReferences
{
	return [self mutableArrayValueForKey:@"multimediaReferences"];
}

@synthesize multimediaEmbeddeds = _multimediaEmbeddeds;
@dynamic mutableMultimediaEmbeddeds;
- (NSMutableArray *)mutableMultimediaEmbeddeds
{
	return [self mutableArrayValueForKey:@"multimediaEmbeddeds"];
}

@synthesize languages = _languages;
@dynamic mutableLanguages;
- (NSMutableArray *)mutableLanguages
{
	return [self mutableArrayValueForKey:@"languages"];
}

@dynamic recordFileNumber;
@dynamic ancestralFileNumber;
@synthesize userReferenceNumbers = _userReferenceNumbers;
@dynamic mutableUserReferenceNumbers;
- (NSMutableArray *)mutableUserReferenceNumbers
{
	return [self mutableArrayValueForKey:@"userReferenceNumbers"];
}

@dynamic recordIdNumber;
@dynamic changeInfo;

@end
