/*
 This file was autogenerated by tags.py 
 */

#import "GCWebAddressAttribute.h"

@implementation GCWebAddressAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a webAddress.

 
 @return A new webAddress.
*/
+(instancetype)webAddress
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a webAddress.

 @param value The value as a GCValue object.
 @return A new webAddress.
*/
+(instancetype)webAddressWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a webAddress.

 @param value The value as an NSString.
 @return A new webAddress.
*/
+(instancetype)webAddressWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
